export const APIS = {
  sample: "/sample",
  total_machine_results:"/api/results/count/",
  total_gx_machines:"/api/machines/count/",
  total_gx_sites:"/api/sites/count/",
  expiring_machine:"/api/machines/expire_machine/",
  calibration_machine:"/api/machines/expire_callib_machine/",
  machine_response:"/api/machines/",
  sites_response:"/api/sites/",
  site_map_result:"api/sites/site_map/",
  machine_status_result:"api/results/get_machine/",
  site_list:"api/sites/gx_list/",
  ticket_list:"/api/tickets/",
  machine_result:"api/results/",
  get_report_data:"api/results/get_report/",
  get_province:"/api/provinces/",
  get_district:"/api/provinces/get_district/",
  get_municipalites:"/api/district/get_municipality/",
  get_ward:"/api/municipality/get_wards/",
  get_health_facility:"/api/wards/get_hi/",
  users:"/api/users/",
};
